<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="main"
    nsURI="http://subkdm/main"
    nsPrefix="main">
  <eSubpackages
      name="subkdm"
      nsURI="http://subkdm/subkdm"
      nsPrefix="h">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CodeModel"
        eSuperTypes="#//subkdm/ModelElement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/AbstractCodeElement"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="AbstractCodeElement"
        abstract="true"
        eSuperTypes="#//subkdm/ModelElement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeRelation"
          upperBound="-1"
          eType="#//kdmRelations/AbstractCodeRelationship"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="comment"
          upperBound="-1"
          eType="#//subkdm/CommentUnit"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CodeItem"
        eSuperTypes="#//subkdm/AbstractCodeElement"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Module"
        eSuperTypes="#//subkdm/CodeItem">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/AbstractCodeElement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Package"
        eSuperTypes="#//subkdm/Module"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="DataType"
        eSuperTypes="#//subkdm/CodeItem"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ClassUnit"
        eSuperTypes="#//subkdm/DataType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/CodeItem"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="isAbstract"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="InterfaceUnit"
        eSuperTypes="#//subkdm/DataType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/CodeItem"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ComputationalObject"
        eSuperTypes="#//subkdm/CodeItem"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ControlElement"
        eSuperTypes="#//subkdm/ComputationalObject">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/AbstractCodeElement"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="type"
          eType="#//subkdm/DataType"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="MethoKind">
      <eLiterals
          name="method"/>
      <eLiterals
          name="constructos"
          value="1"/>
      <eLiterals
          name="destructor"
          value="2"/>
      <eLiterals
          name="operator"
          value="3"/>
      <eLiterals
          name="virtual"
          value="4"/>
      <eLiterals
          name="abstract"
          value="5"/>
      <eLiterals
          name="unknown"
          value="6"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="CallableKind">
      <eLiterals
          name="external"/>
      <eLiterals
          name="regular"
          value="1"/>
      <eLiterals
          name="operator"
          value="2"/>
      <eLiterals
          name="stored"
          value="3"/>
      <eLiterals
          name="unknown"
          value="4"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CallableUnit"
        eSuperTypes="#//subkdm/ControlElement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="kind"
          eType="#//subkdm/MethoKind"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="MethodUnit"
        eSuperTypes="#//subkdm/ControlElement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="kind"
          eType="#//subkdm/CallableKind"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="DataElement"
        eSuperTypes="#//subkdm/ComputationalObject">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/DataType"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="type"
          lowerBound="1"
          eType="#//subkdm/DataType"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="ext"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="size"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="StorableUnit"
        eSuperTypes="#//subkdm/DataElement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="kind"
          eType="#//subkdm/StorableKind"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="StorableKind">
      <eLiterals
          name="global"/>
      <eLiterals
          name="local"
          value="1"/>
      <eLiterals
          name="static"
          value="2"/>
      <eLiterals
          name="external"
          value="3"/>
      <eLiterals
          name="register"
          value="4"/>
      <eLiterals
          name="unknown"
          value="5"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="ExportKind">
      <eLiterals
          name="public"/>
      <eLiterals
          name="private"
          value="1"/>
      <eLiterals
          name="protected"
          value="2"/>
      <eLiterals
          name="final"
          value="3"/>
      <eLiterals
          name="unknown"
          value="4"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CommentUnit">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="text"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ParameterUnit"
        eSuperTypes="#//subkdm/DataElement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="kind"
          eType="#//subkdm/ParameterKind"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="pos"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="TemplateUnit"
        eSuperTypes="#//subkdm/DataType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/CodeUnit"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CodeUnit"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Signature"
        eSuperTypes="#//subkdm/DataType">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="parameterUnit"
          upperBound="-1"
          eType="#//subkdm/ParameterUnit"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ActionElement"
        eSuperTypes="#//subkdm/AbstractCodeElement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="kind"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="codeElement"
          upperBound="-1"
          eType="#//subkdm/AbstractCodeElement"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="actionRelation"
          upperBound="-1"
          eType="#//kdmRelations/AbstractActionRelationship"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="BlockUnit"
        eSuperTypes="#//subkdm/ActionElement"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ExceptionUnit"
        eSuperTypes="#//subkdm/BlockUnit"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="TryUnit"
        eSuperTypes="#//subkdm/ExceptionUnit"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="CatchUnit"
        eSuperTypes="#//subkdm/ExceptionUnit"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="FinallyUnit"
        eSuperTypes="#//subkdm/ExceptionUnit"/>
    <eClassifiers
        xsi:type="ecore:EEnum"
        name="ParameterKind">
      <eLiterals
          name="byValue"/>
      <eLiterals
          name="byName"
          value="1"/>
      <eLiterals
          name="byReference"
          value="2"/>
      <eLiterals
          name="variadic"
          value="3"/>
      <eLiterals
          name="return"
          value="4"/>
      <eLiterals
          name="throws"
          value="5"/>
      <eLiterals
          name="exception"
          value="6"/>
      <eLiterals
          name="catchall"
          value="7"/>
      <eLiterals
          name="unknown"
          value="8"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Segment"
        eSuperTypes="#//subkdm/ModelElement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="model"
          upperBound="-1"
          eType="#//subkdm/CodeModel"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ModelElement"/>
  </eSubpackages>
  <eSubpackages
      name="SimplifiedDecisionMetrics"
      nsURI="http://subkdm/sdm"
      nsPrefix="sdm">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Observation">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="whenObserved"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="measures"
          upperBound="-1"
          eType="#//SimplifiedDecisionMetrics/Measure"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Measure">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="measurements"
          upperBound="-1"
          eType="#//SimplifiedDecisionMetrics/Measurement"
          containment="true"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="name"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="description"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Measurement"
        abstract="true">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="measurant"
          eType="#//SimplifiedDecisionMetrics/MofElement"
          eOpposite="#//SimplifiedDecisionMetrics/MofElement/measurant"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Grade"
        eSuperTypes="#//SimplifiedDecisionMetrics/Measurement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="value"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="DimensionalMeasurement"
        eSuperTypes="#//SimplifiedDecisionMetrics/Measurement">
      <eStructuralFeatures
          xsi:type="ecore:EAttribute"
          name="value"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="SimplifiedDecisionMetrics">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="observations"
          upperBound="-1"
          eType="#//SimplifiedDecisionMetrics/Observation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="MofElement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="measurant"
          upperBound="-1"
          eType="#//SimplifiedDecisionMetrics/Measurement"
          eOpposite="#//SimplifiedDecisionMetrics/Measurement/measurant"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="element"
          eType="#//subkdm/ModelElement"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages
      name="kdmRelations">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="AbstractCodeRelationship">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="to"
          lowerBound="1"
          eType="#//subkdm/AbstractCodeElement"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="from"
          lowerBound="1"
          eType="#//subkdm/AbstractCodeElement"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Calls"
        eSuperTypes="#//kdmRelations/AbstractActionRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Reads"
        eSuperTypes="#//kdmRelations/AbstractActionRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Writes"
        eSuperTypes="#//kdmRelations/AbstractActionRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Creates"
        eSuperTypes="#//kdmRelations/AbstractActionRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ImplementationOf"
        eSuperTypes="#//kdmRelations/AbstractCodeRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="HasValue"
        eSuperTypes="#//kdmRelations/AbstractCodeRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Imports"
        eSuperTypes="#//kdmRelations/AbstractCodeRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Implements"
        eSuperTypes="#//kdmRelations/AbstractCodeRelationship"/>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="AbstractActionRelationship"
        eSuperTypes="#//subkdm/ModelElement">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="to"
          lowerBound="1"
          eType="#//subkdm/AbstractCodeElement"/>
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="from"
          lowerBound="1"
          eType="#//subkdm/AbstractCodeElement"/>
    </eClassifiers>
    <eClassifiers
        xsi:type="ecore:EClass"
        name="Extends"
        eSuperTypes="#//kdmRelations/AbstractCodeRelationship"/>
  </eSubpackages>
</ecore:EPackage>
