<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="subkdm" nsURI="http://subkdm/1.0" nsPrefix="subkdm">
  <eClassifiers xsi:type="ecore:EClass" name="CodeModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//AbstractCodeElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCodeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeRelation" upperBound="-1"
        eType="#//AbstractCodeRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//CommentUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCodeRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CodeItem" eSuperTypes="#//AbstractCodeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//CodeItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//AbstractCodeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//CodeItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassUnit" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//CodeItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceUnit" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//CodeItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationalObject" eSuperTypes="#//CodeItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlElement" eSuperTypes="#//ComputationalObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//AbstractCodeElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MethoKind">
    <eLiterals name="method"/>
    <eLiterals name="constructos" value="1"/>
    <eLiterals name="destructor" value="2"/>
    <eLiterals name="operator" value="3"/>
    <eLiterals name="virtual" value="4"/>
    <eLiterals name="abstract" value="5"/>
    <eLiterals name="unknown" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallableKind">
    <eLiterals name="external"/>
    <eLiterals name="regular" value="1"/>
    <eLiterals name="operator" value="2"/>
    <eLiterals name="stored" value="3"/>
    <eLiterals name="unknown" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallableUnit" eSuperTypes="#//ControlElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//MethoKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodUnit" eSuperTypes="#//ControlElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CallableKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" eSuperTypes="#//ComputationalObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorableUnit" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//StorableKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorableKind">
    <eLiterals name="global"/>
    <eLiterals name="local" value="1"/>
    <eLiterals name="static" value="2"/>
    <eLiterals name="external" value="3"/>
    <eLiterals name="register" value="4"/>
    <eLiterals name="unknown" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExportKind">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="final" value="3"/>
    <eLiterals name="unknown" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Imports" eSuperTypes="#//AbstractCodeRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//CodeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//CodeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implements" eSuperTypes="#//AbstractCodeRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//CodeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//CodeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extends" eSuperTypes="#//AbstractCodeRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterUnit" eSuperTypes="#//DataElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ParameterKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateUnit" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//CodeUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterUnit" upperBound="-1"
        eType="#//ParameterUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplementationOf" eSuperTypes="#//AbstractCodeRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//CodeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//CodeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasValue" eSuperTypes="#//AbstractCodeRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//CodeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//AbstractCodeElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElement" upperBound="-1"
        eType="#//AbstractCodeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockUnit" eSuperTypes="#//ActionElement #//ExceptionUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="TryUnit" eSuperTypes="#//ExceptionUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="CatchUnit" eSuperTypes="#//ExceptionUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinallyUnit" eSuperTypes="#//ExceptionUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractActionRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Calls" eSuperTypes="#//AbstractActionRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//ActionElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ControlElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reads" eSuperTypes="#//AbstractActionRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//ActionElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Writes" eSuperTypes="#//AbstractActionRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//ActionElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DataElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Creates" eSuperTypes="#//AbstractActionRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//ActionElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterKind">
    <eLiterals name="byValue"/>
    <eLiterals name="byName" value="1"/>
    <eLiterals name="byReference" value="2"/>
    <eLiterals name="variadic" value="3"/>
    <eLiterals name="return" value="4"/>
    <eLiterals name="throws" value="5"/>
    <eLiterals name="exception" value="6"/>
    <eLiterals name="catchall" value="7"/>
    <eLiterals name="unknown" value="8"/>
  </eClassifiers>
</ecore:EPackage>
