<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visualizacionMetricas2" nsURI="http://www.example.org/visualizacionMetricas2"
    nsPrefix="visualizacionMetricas2">
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clusters" upperBound="-1"
        eType="#//Cluster" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento" abstract="true" eSuperTypes="#//Medible">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencias" upperBound="-1"
        eType="#//Dependencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodo" eSuperTypes="#//Elemento">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hijos" upperBound="-1"
        eType="#//Elemento" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Nodo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependencia" eSuperTypes="#//Medible">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependiente" eType="#//Elemento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiposrelacion" upperBound="-1"
        eType="#//TipoRelacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricaDibujable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tamanio" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intensidad" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complejidad" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Medible" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metricas" upperBound="-1"
        eType="#//MetricaDibujable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoRelacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
