<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="visualizacionMetricas" nsURI="http://www.example.org/visualizacionMetricas"
    nsPrefix="visualizacionMetricas">
  <eClassifiers xsi:type="ecore:EClass" name="Elemento" abstract="true" eSuperTypes="#//Medible">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciones" upperBound="-1"
        eType="#//Arco" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoElemento"
        defaultValueLiteral="NODO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodo" eSuperTypes="#//Elemento">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hijos" upperBound="-1"
        eType="#//Elemento" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hoja" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Medible" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metricas" upperBound="-1"
        eType="#//Metrica" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arco" eSuperTypes="#//Medible">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Elemento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipos" upperBound="-1"
        eType="#//TipoArco" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metrica">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoMetrica"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoElemento">
    <eLiterals name="NODO"/>
    <eLiterals name="CLUSTER" value="1"/>
    <eLiterals name="PACKAGE" value="2"/>
    <eLiterals name="CLASS" value="3"/>
    <eLiterals name="APLICACION" value="4" literal="APLICACION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoArco">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoMetrica">
    <eLiterals name="CalculatedCoupling"/>
    <eLiterals name="WeightedMethodsPerClass" value="1"/>
    <eLiterals name="NumberOfUses" value="2"/>
    <eLiterals name="NumberOfContainments" value="3"/>
    <eLiterals name="CouplingBetweenObjects" value="4" literal="CouplingBetweenObjects"/>
  </eClassifiers>
  <eSubpackages name="representacion" nsURI="http://www.example.org/visualizacionMetricas3/representacion"
      nsPrefix="visualizacionMetricas3.representacion">
    <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Paquete" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Modulo" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Clase" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Archivo" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Servicio" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Tabla" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Aplicacion" eSuperTypes="#//Nodo"/>
  </eSubpackages>
  <eSubpackages name="visualizacion" nsURI="http://www.example.org/visualizacionMetricas3/visualizacion"
      nsPrefix="visualizacionMetricas3.visualizacion">
    <eClassifiers xsi:type="ecore:EClass" name="Elipse" eSuperTypes="#//visualizacion/FiguraGeometrica"/>
    <eClassifiers xsi:type="ecore:EClass" name="Cuadrilatero" eSuperTypes="#//visualizacion/FiguraGeometrica"/>
    <eClassifiers xsi:type="ecore:EClass" name="Contenedor" abstract="true" interface="true"
        eSuperTypes="#//Nodo"/>
    <eClassifiers xsi:type="ecore:EClass" name="Clase" eSuperTypes="#//visualizacion/Contenedor"/>
    <eClassifiers xsi:type="ecore:EClass" name="FiguraGeometrica" abstract="true"
        interface="true" eSuperTypes="#//Elemento">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//visualizacion/Color"
          defaultValueLiteral="white"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="largo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Color">
      <eLiterals name="white"/>
      <eLiterals name="black" value="1"/>
      <eLiterals name="blue" value="2"/>
      <eLiterals name="chocolate" value="3"/>
      <eLiterals name="gray" value="4"/>
      <eLiterals name="green" value="5"/>
      <eLiterals name="orange" value="6"/>
      <eLiterals name="purple" value="7"/>
      <eLiterals name="red" value="8"/>
      <eLiterals name="yellow" value="9"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rombo" eSuperTypes="#//visualizacion/FiguraGeometrica"/>
    <eClassifiers xsi:type="ecore:EClass" name="Triangulo" eSuperTypes="#//visualizacion/FiguraGeometrica"/>
  </eSubpackages>
</ecore:EPackage>
